name: test

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Nextflow
      run: |
        curl -s https://get.nextflow.io | bash
        sudo mv nextflow /usr/local/bin/
    - name: Run movp test
      run: |
        nextflow run marine-omics/movp -profile docker,test -r main
    - name: Show nextflow log
        cat .nextflow.log

