name: test

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Nextflow
      run: |
        curl -s https://get.nextflow.io | bash
        sudo mv nextflow /usr/local/bin/
    - name: Run movp test
      run: |
        nextflow run marine-omics/movp -profile docker,test -r main --callers gatk
    - name: Whereami
      if: always()
      run: |
        pwd
        ls -a 
    - name: Archive nextflow log
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: Nextflow logs
        path: .nextflow.log
